name = "LibNeo"
uuid = "b33e9245-94c4-4252-b447-c7b9d305653a"
authors = ["Christopher Albert <albert@tugraz.at>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BenchmarkTools = "1.6.0"
Test = "1.11.0"
